# Generated by Django 5.0.6 on 2024-05-26 22:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('text', models.TextField()),
                ('datePublished', models.DateField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('url', models.URLField()),
                ('author', models.TextField(blank=True, null=True)),
                ('alternateName', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalType', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('text__isnull', False), ('datePublished__isnull', False), ('url__isnull', False)), name='required_fields'),
        ),
    ]
