# Generated by Django 5.0.6 on 2024-06-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmapp', '0002_alter_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='additionalType',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='alternateName',
            field=models.CharField(blank=True, null=True),
        ),
    ]
