# Generated by Django 5.0.6 on 2024-06-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmapp', '0003_alter_document_additionaltype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='additionalType',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='alternateName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
