# Generated by Django 5.0.4 on 2024-05-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datePublished', models.DateField()),
                ('dateCreated', models.DateField()),
                ('author', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
